### ISSUE TITLE
[Feature Request]: Add CI GitHub Actions for linting, tests, and build

### ISSUE THREAD

**Issue by Producdevity** [Producdevity/EmuReady#25]
## Description

Automated checks are needed to stop PRs that break linting, unit tests, or the production build.

## Describe the solution you'd like
Add `.github/workflows/ci.yml` that runs on every `pull_request` (and propably also `push` to `main`):

Example config:
```yaml
name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Lint & type-check
        run: npm run check
      - name: Unit tests
        run: npm run test:ci
      - name: Build
        run: npm run build
      # - name: E2E tests (enable when ready)
      #   run: npm run test:e2e:ci
      #   if: false
```

## Additional context

- Node 20 image.
- Dependency caching via setup-node.
- `npm run test:e2e:ci` step present but disabled until the Playwright suite passes.
- Protect main branch with the new workflow status check.

## Tasks

- Add ci.yml as above.
- Configure branch protection to require the CI check.
- Add a CI badge to README.md.
- Enable npm run test:e2e:ci once the E2E suite is green. (have is disabled, make it non-required, or commented out for now)

## Checklist

- [x] I have checked that this feature request has not already been suggested
- [x] I have provided sufficient context and motivation
- [x] I am willing to help implement this feature if needed
